name: Lint and Build
on: [ pull_request, push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup Node packages
        run: npm ci
      - name: Lint files
        run: npm run lint
      - name: Test project
        run: npm run test --watch=false
      - name: Build project
        run: npm run build
      - name: Capture main build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Main
          path: dist/angular-placeholder-task/browser
